create table if not exists public.upload_history (
  id bigint generated by default as identity primary key,
  filename text not null,
  file_type text not null,
  uploaded_at timestamptz not null default now(),
  status text not null check (status in ('success', 'error', 'processing')),
  rows_processed integer,
  error_lines integer not null default 0,
  notes text
);

create index if not exists upload_history_uploaded_at_idx on public.upload_history (uploaded_at desc);
create index if not exists upload_history_status_idx on public.upload_history (status);

create table if not exists public.dashboard_uploads (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('invoice', 'payment')),
  filename text not null,
  sheet_name text not null,
  mime_type text,
  file_size integer not null,
  file_sha256 text not null,
  file_data bytea not null,
  dashboard_data jsonb not null,
  section_data jsonb not null,
  total_amount numeric not null,
  row_count integer not null,
  uploaded_at timestamptz not null default now()
);

create index if not exists dashboard_uploads_role_uploaded_at_idx
  on public.dashboard_uploads (role, uploaded_at desc);

create index if not exists dashboard_uploads_file_sha256_idx
  on public.dashboard_uploads (file_sha256);

insert into public.upload_history (filename, file_type, uploaded_at, status, rows_processed, error_lines, notes)
values
  ('Q3_Invoices_EU.xlsx', 'Invoice', '2023-10-24 14:32:00+00', 'success', 4250, 0, 'Stable import and normalized vendor mapping.'),
  ('Oct_Payroll_Batch.csv', 'Payment', '2023-10-23 09:15:00+00', 'error', 1120, 3, 'Three lines failed due to malformed account identifiers.'),
  ('Vendor_List_Update.xlsx', 'Master Data', '2023-10-21 16:45:00+00', 'success', 84, 0, 'Reference list refreshed without conflicts.'),
  ('Q4_Forecast_Draft.xlsx', 'Forecast', now(), 'processing', null, 0, 'Validation is still running for this draft.')
on conflict do nothing;
