import "server-only";

import { createHash } from "node:crypto";

import {
  buildSection,
  buildMonitoringDashboardFromFiles,
  groupByPeriod,
  parseRecordsFromWorkbook,
  type BaseRecord,
} from "@/lib/monitoring-dashboard";
import { packRows } from "@/lib/packed-rows";
import { getPostgresPool } from "@/lib/postgres";
import type {
  DashboardMonthMeta,
  DashboardPayload,
  DashboardRecord,
  PackedDashboardReport,
  DashboardSection,
  MonitoringDashboardData,
  PersistedDashboardReport,
  PersistedDashboardReports,
  UploadedWorkbookSummary,
  WorkbookRole,
} from "@/lib/monitoring-dashboard-types";

type SaveDashboardUploadInput = {
  role: WorkbookRole;
  file: {
    name: string;
    type: string;
    size: number;
    buffer: Buffer;
  };
  dashboardData: MonitoringDashboardData;
  fileSummary: UploadedWorkbookSummary;
  section: DashboardSection;
};

type DashboardUploadRow = {
  id: string;
  role: WorkbookRole;
  filename: string;
  sheet_name: string;
  row_count: number;
  total_amount: string;
  section_data: DashboardSection;
  file_data?: Buffer;
  uploaded_at: string;
};

let schemaPromise: Promise<void> | null = null;

function ensureSchema() {
  schemaPromise ??= getPostgresPool()
    .query(`
      create table if not exists public.dashboard_uploads (
        id bigint generated by default as identity primary key,
        role text not null check (role in ('invoice', 'payment')),
        filename text not null,
        sheet_name text not null,
        mime_type text,
        file_size integer not null,
        file_sha256 text not null,
        file_data bytea not null,
        dashboard_data jsonb not null,
        section_data jsonb not null,
        total_amount numeric not null,
        row_count integer not null,
        uploaded_at timestamptz not null default now()
      );

      create index if not exists dashboard_uploads_role_uploaded_at_idx
        on public.dashboard_uploads (role, uploaded_at desc);

      create index if not exists dashboard_uploads_file_sha256_idx
        on public.dashboard_uploads (file_sha256);
    `)
    .then(() => undefined);

  return schemaPromise;
}

function hasFilterRecords(section: DashboardSection) {
  return Array.isArray((section as DashboardSection & { records?: unknown }).records);
}

async function sectionWithFilterRecords(row: DashboardUploadRow) {
  if (hasFilterRecords(row.section_data) || !row.file_data) {
    return row.section_data;
  }

  try {
    const dashboard = buildMonitoringDashboardFromFiles(
      [
        {
          name: row.filename,
          buffer: row.file_data,
        },
      ],
      row.role,
    );

    const section = dashboard[row.role] ?? row.section_data;

    if (hasFilterRecords(section)) {
      await getPostgresPool().query(
        `
          update public.dashboard_uploads
          set section_data = $1::jsonb
          where id = $2;
        `,
        [JSON.stringify(section), row.id],
      );
    }

    return section;
  } catch {
    return row.section_data;
  }
}

async function toPersistedReport(row: DashboardUploadRow): Promise<PersistedDashboardReport> {
  const role = row.role;
  const section = await sectionWithFilterRecords(row);

  return {
    id: Number(row.id),
    role,
    generatedAt: row.uploaded_at,
    file: {
      role,
      name: row.filename,
      sheetName: row.sheet_name,
      rowCount: row.row_count,
      totalAmount: Number(row.total_amount),
    },
    section,
  };
}

export async function saveDashboardUpload(input: SaveDashboardUploadInput): Promise<PersistedDashboardReport> {
  await ensureSchema();

  const fileHash = createHash("sha256").update(input.file.buffer).digest("hex");
  const result = await getPostgresPool().query<DashboardUploadRow>(
    `
      insert into public.dashboard_uploads (
        role,
        filename,
        sheet_name,
        mime_type,
        file_size,
        file_sha256,
        file_data,
        dashboard_data,
        section_data,
        total_amount,
        row_count
      )
      values ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9::jsonb, $10, $11)
      returning id, role, filename, sheet_name, row_count, total_amount::text, section_data, uploaded_at::text;
    `,
    [
      input.role,
      input.file.name,
      input.fileSummary.sheetName,
      input.file.type || "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      input.file.size,
      fileHash,
      input.file.buffer,
      JSON.stringify(input.dashboardData),
      JSON.stringify(input.section),
      input.fileSummary.totalAmount,
      input.fileSummary.rowCount,
    ],
  );

  return toPersistedReport(result.rows[0]);
}

export async function getLatestDashboardReports(role?: WorkbookRole): Promise<PersistedDashboardReports> {
  await ensureSchema();

  const result = await getPostgresPool().query<DashboardUploadRow>(
    role
      ? `
        select distinct on (role)
          id, role, filename, sheet_name, row_count, total_amount::text, section_data,
          case when section_data ? 'records' then null else file_data end as file_data,
          uploaded_at::text
        from public.dashboard_uploads
        where role = $1
        order by role, uploaded_at desc;
      `
      : `
        select distinct on (role)
          id, role, filename, sheet_name, row_count, total_amount::text, section_data,
          case when section_data ? 'records' then null else file_data end as file_data,
          uploaded_at::text
        from public.dashboard_uploads
        order by role, uploaded_at desc;
      `,
    role ? [role] : [],
  );

  const persistedReports = await Promise.all(result.rows.map((row) => toPersistedReport(row)));

  return persistedReports.reduce<PersistedDashboardReports>((reports, report) => {
    reports[report.role] = report;
    return reports;
  }, {});
}

// ---------------------------------------------------------------------------
// Per-month storage (dashboard_records)
// ---------------------------------------------------------------------------
// One row = one Excel record tagged with its month (period_key). Uploading a
// month upserts only that month (old rows for the period are deleted, new ones
// inserted). Deleting a month removes only that period's rows. This is what
// lets the client "upload just this month" and "delete just one month".

let recordsSchemaPromise: Promise<void> | null = null;
const DASHBOARD_RECORD_INSERT_CHUNK_SIZE = 1000;

function ensureRecordsSchema() {
  recordsSchemaPromise ??= getPostgresPool()
    .query(`
      create table if not exists public.dashboard_records (
        id bigint generated by default as identity primary key,
        role text not null check (role in ('invoice', 'payment')),
        period_key text not null,
        source_filename text not null,
        amount numeric not null,
        customer_name text,
        customer_type text,
        invoice_type text,
        status text,
        document_number text,
        risk_status text,
        uploaded_at timestamptz not null default now()
      );

      create index if not exists dashboard_records_role_period_idx
        on public.dashboard_records (role, period_key);

      create index if not exists dashboard_records_role_uploaded_at_idx
        on public.dashboard_records (role, uploaded_at desc);
    `)
    .then(() => undefined);

  return recordsSchemaPromise;
}

type DashboardRecordRow = {
  period_key: string;
  amount: string;
  row_count: number;
  customer_name: string | null;
  customer_type: string | null;
  invoice_type: string | null;
  status: string | null;
};

function monthLabelFromPeriodKey(periodKey: string) {
  const [yearStr, monthStr] = periodKey.split("-");
  const year = Number(yearStr);
  const month = Number(monthStr);
  const MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"];

  if (!Number.isFinite(year) || !Number.isFinite(month) || month < 1 || month > 12) {
    return periodKey;
  }

  return `${MONTHS[month]} ${year}`;
}

function recordToDashboardRecord(row: DashboardRecordRow): DashboardRecord {
  const periodKey = row.period_key;
  const periodLabel = monthLabelFromPeriodKey(periodKey);
  const [year, month] = periodKey.split("-").map(Number);
  const periodSort = Number.isFinite(year) && Number.isFinite(month) ? year * 100 + month : null;

  return {
    amount: Number(row.amount),
    customerName: row.customer_name ?? "Unmapped",
    customerType: row.customer_type ?? "Unmapped",
    invoiceType: row.invoice_type ?? "Unmapped",
    status: row.status ?? "Unmapped",
    periodKey,
    periodLabel,
    periodSort,
    count: row.row_count,
  };
}

type StoredMonthMeta = {
  period_key: string;
  row_count: number;
  total_amount: string;
  latest_uploaded_at: string;
};

export type StoredMonth = DashboardMonthMeta;

// Every dashboard filter works on these five dimensions, so rows that share
// all of them are merged in SQL (amount summed, row count kept in `count`).
// The client gets the exact same totals with ~40% fewer records.
async function loadAggregatedRecords(role: WorkbookRole): Promise<DashboardRecord[]> {
  await ensureRecordsSchema();

  const result = await getPostgresPool().query<DashboardRecordRow>(
    `
      select period_key, sum(amount)::text as amount, count(*)::int as row_count,
             customer_name, customer_type, invoice_type, status
      from public.dashboard_records
      where role = $1
      group by period_key, customer_name, customer_type, invoice_type, status
      order by period_key asc;
    `,
    [role],
  );

  return result.rows.map(recordToDashboardRecord);
}

export async function listAvailableMonthsForRole(role: WorkbookRole): Promise<StoredMonth[]> {
  await ensureRecordsSchema();

  const result = await getPostgresPool().query<StoredMonthMeta>(
    `
      select period_key, count(*)::int as row_count, sum(amount)::text as total_amount,
             max(uploaded_at)::text as latest_uploaded_at
      from public.dashboard_records
      where role = $1
      group by period_key
      order by period_key desc;
    `,
    [role],
  );

  return result.rows.map((row) => ({
    periodKey: row.period_key,
    label: monthLabelFromPeriodKey(row.period_key),
    rowCount: row.row_count,
    totalAmount: Number(row.total_amount),
    uploadedAt: row.latest_uploaded_at,
  }));
}

export type RoleDashboard = { report?: PackedDashboardReport; months: StoredMonth[] };

export async function getRoleDashboard(role: WorkbookRole): Promise<RoleDashboard> {
  const [records, months] = await Promise.all([loadAggregatedRecords(role), listAvailableMonthsForRole(role)]);

  if (records.length === 0) {
    return { months };
  }

  const latestMonth = months[0];

  return {
    months,
    report: {
      role,
      generatedAt: latestMonth?.uploadedAt ?? new Date().toISOString(),
      file: {
        role,
        name: latestMonth ? `Merge ${months.length} bulan` : "Dashboard",
        sheetName: role === "invoice" ? "Billing Detail" : "Detail Payment",
        rowCount: months.reduce((total, month) => total + month.rowCount, 0),
        totalAmount: months.reduce((total, month) => total + month.totalAmount, 0),
      },
      records: packRows(records.map(({ periodLabel: _label, periodSort: _sort, ...record }) => record)),
    },
  };
}

export function toDashboardPayload(entries: (readonly [WorkbookRole, RoleDashboard])[]): DashboardPayload {
  const payload: DashboardPayload = { reports: {}, months: {} };

  for (const [role, dashboard] of entries) {
    payload.months[role] = dashboard.months;
    if (dashboard.report) payload.reports[role] = dashboard.report;
  }

  return payload;
}

// Replace every month present in the workbook inside ONE transaction on ONE
// connection: a single bulk delete, then chunked unnest() inserts. Running a
// transaction per month in parallel opened N pool connections against the
// remote Postgres and made multi-month uploads slow.
async function replaceMonthRecords(role: WorkbookRole, byPeriod: Map<string, BaseRecord[]>, sourceFilename: string) {
  await ensureRecordsSchema();

  const rows = [...byPeriod.entries()].flatMap(([periodKey, records]) => records.map((record) => ({ periodKey, record })));
  const client = await getPostgresPool().connect();

  try {
    await client.query("begin");
    await client.query(`delete from public.dashboard_records where role = $1 and period_key = any($2::text[]);`, [role, [...byPeriod.keys()]]);

    for (let start = 0; start < rows.length; start += DASHBOARD_RECORD_INSERT_CHUNK_SIZE) {
      const chunk = rows.slice(start, start + DASHBOARD_RECORD_INSERT_CHUNK_SIZE);

      await client.query(
        `
          insert into public.dashboard_records (
            role, period_key, source_filename, amount,
            customer_name, customer_type, invoice_type, status,
            document_number, risk_status
          )
          select
            $1::text,
            record.period_key,
            $2::text,
            record.amount,
            record.customer_name,
            record.customer_type,
            record.invoice_type,
            record.status,
            record.document_number,
            record.risk_status
          from unnest(
            $3::text[],
            $4::numeric[],
            $5::text[],
            $6::text[],
            $7::text[],
            $8::text[],
            $9::text[],
            $10::text[]
          ) as record(
            period_key,
            amount,
            customer_name,
            customer_type,
            invoice_type,
            status,
            document_number,
            risk_status
          );
        `,
        [
          role,
          sourceFilename,
          chunk.map(({ periodKey }) => periodKey),
          chunk.map(({ record }) => record.amount),
          chunk.map(({ record }) => record.customerName),
          chunk.map(({ record }) => record.customerType),
          chunk.map(({ record }) => record.invoiceType),
          chunk.map(({ record }) => record.status),
          chunk.map(({ record }) => (record as BaseRecord & { documentNumber?: string }).documentNumber ?? null),
          chunk.map(({ record }) => (record as BaseRecord & { riskStatus?: string }).riskStatus ?? null),
        ],
      );
    }

    await client.query("commit");
  } catch (error) {
    await client.query("rollback");
    throw error;
  } finally {
    client.release();
  }
}

export async function deleteMonthRecords(role: WorkbookRole, periodKey: string): Promise<{ deleted: number }> {
  await ensureRecordsSchema();

  const result = await getPostgresPool().query(
    `delete from public.dashboard_records where role = $1 and period_key = $2;`,
    [role, periodKey],
  );

  return { deleted: result.rowCount ?? 0 };
}

// Upload handler for the per-month merge model: parse the workbook, group its
// records by period, and replace each of those periods. A workbook with many
// months (initial bulk upload) stores each month separately; a single-month
// workbook only touches that one month.
export async function saveDashboardUploadByMonth(
  role: WorkbookRole,
  file: { name: string; buffer: Buffer },
): Promise<{ upsertedMonths: { periodKey: string; rowCount: number }[] }> {
  const records = parseRecordsFromWorkbook(file, role);

  if (records.length === 0) {
    throw new Error("Tidak ada record valid yang bisa dibaca dari workbook.");
  }

  const byPeriod = groupByPeriod(records);

  if (byPeriod.size === 0) {
    throw new Error("Record di workbook tidak memiliki periode (bulan/tahun) atau tanggal yang bisa dibaca.");
  }

  await replaceMonthRecords(role, byPeriod, file.name);

  return {
    upsertedMonths: [...byPeriod.entries()].map(([periodKey, periodRecords]) => ({ periodKey, rowCount: periodRecords.length })),
  };
}

// Re-exported so the legacy snapshot path keeps compiling if still referenced.
export async function computeFileSha256(buffer: Buffer) {
  return createHash("sha256").update(buffer).digest("hex");
}

// Kept to satisfy the unused buildSection import usage in legacy snapshot path.
export { buildSection };
