import "server-only";

import { createHash } from "node:crypto";

import {
  buildSection,
  buildSectionFromDbRecords,
  buildMonitoringDashboardFromFiles,
  groupByPeriod,
  parseRecordsFromWorkbook,
  statusOrderByRole,
  type BaseRecord,
} from "@/lib/monitoring-dashboard";
import { getPostgresPool } from "@/lib/postgres";
import type {
  DashboardRecord,
  DashboardSection,
  MonitoringDashboardData,
  PersistedDashboardReport,
  PersistedDashboardReports,
  UploadedWorkbookSummary,
  WorkbookRole,
} from "@/lib/monitoring-dashboard-types";

type SaveDashboardUploadInput = {
  role: WorkbookRole;
  file: {
    name: string;
    type: string;
    size: number;
    buffer: Buffer;
  };
  dashboardData: MonitoringDashboardData;
  fileSummary: UploadedWorkbookSummary;
  section: DashboardSection;
};

type DashboardUploadRow = {
  id: string;
  role: WorkbookRole;
  filename: string;
  sheet_name: string;
  row_count: number;
  total_amount: string;
  section_data: DashboardSection;
  file_data?: Buffer;
  uploaded_at: string;
};

let schemaPromise: Promise<void> | null = null;

function ensureSchema() {
  schemaPromise ??= getPostgresPool()
    .query(`
      create table if not exists public.dashboard_uploads (
        id bigint generated by default as identity primary key,
        role text not null check (role in ('invoice', 'payment')),
        filename text not null,
        sheet_name text not null,
        mime_type text,
        file_size integer not null,
        file_sha256 text not null,
        file_data bytea not null,
        dashboard_data jsonb not null,
        section_data jsonb not null,
        total_amount numeric not null,
        row_count integer not null,
        uploaded_at timestamptz not null default now()
      );

      create index if not exists dashboard_uploads_role_uploaded_at_idx
        on public.dashboard_uploads (role, uploaded_at desc);

      create index if not exists dashboard_uploads_file_sha256_idx
        on public.dashboard_uploads (file_sha256);
    `)
    .then(() => undefined);

  return schemaPromise;
}

function hasFilterRecords(section: DashboardSection) {
  return Array.isArray((section as DashboardSection & { records?: unknown }).records);
}

async function sectionWithFilterRecords(row: DashboardUploadRow) {
  if (hasFilterRecords(row.section_data) || !row.file_data) {
    return row.section_data;
  }

  try {
    const dashboard = buildMonitoringDashboardFromFiles(
      [
        {
          name: row.filename,
          buffer: row.file_data,
        },
      ],
      row.role,
    );

    const section = dashboard[row.role] ?? row.section_data;

    if (hasFilterRecords(section)) {
      await getPostgresPool().query(
        `
          update public.dashboard_uploads
          set section_data = $1::jsonb
          where id = $2;
        `,
        [JSON.stringify(section), row.id],
      );
    }

    return section;
  } catch {
    return row.section_data;
  }
}

async function toPersistedReport(row: DashboardUploadRow): Promise<PersistedDashboardReport> {
  const role = row.role;
  const section = await sectionWithFilterRecords(row);

  return {
    id: Number(row.id),
    role,
    generatedAt: row.uploaded_at,
    file: {
      role,
      name: row.filename,
      sheetName: row.sheet_name,
      rowCount: row.row_count,
      totalAmount: Number(row.total_amount),
    },
    section,
  };
}

export async function saveDashboardUpload(input: SaveDashboardUploadInput): Promise<PersistedDashboardReport> {
  await ensureSchema();

  const fileHash = createHash("sha256").update(input.file.buffer).digest("hex");
  const result = await getPostgresPool().query<DashboardUploadRow>(
    `
      insert into public.dashboard_uploads (
        role,
        filename,
        sheet_name,
        mime_type,
        file_size,
        file_sha256,
        file_data,
        dashboard_data,
        section_data,
        total_amount,
        row_count
      )
      values ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9::jsonb, $10, $11)
      returning id, role, filename, sheet_name, row_count, total_amount::text, section_data, uploaded_at::text;
    `,
    [
      input.role,
      input.file.name,
      input.fileSummary.sheetName,
      input.file.type || "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      input.file.size,
      fileHash,
      input.file.buffer,
      JSON.stringify(input.dashboardData),
      JSON.stringify(input.section),
      input.fileSummary.totalAmount,
      input.fileSummary.rowCount,
    ],
  );

  return toPersistedReport(result.rows[0]);
}

export async function getLatestDashboardReports(role?: WorkbookRole): Promise<PersistedDashboardReports> {
  await ensureSchema();

  const result = await getPostgresPool().query<DashboardUploadRow>(
    role
      ? `
        select distinct on (role)
          id, role, filename, sheet_name, row_count, total_amount::text, section_data,
          case when section_data ? 'records' then null else file_data end as file_data,
          uploaded_at::text
        from public.dashboard_uploads
        where role = $1
        order by role, uploaded_at desc;
      `
      : `
        select distinct on (role)
          id, role, filename, sheet_name, row_count, total_amount::text, section_data,
          case when section_data ? 'records' then null else file_data end as file_data,
          uploaded_at::text
        from public.dashboard_uploads
        order by role, uploaded_at desc;
      `,
    role ? [role] : [],
  );

  const persistedReports = await Promise.all(result.rows.map((row) => toPersistedReport(row)));

  return persistedReports.reduce<PersistedDashboardReports>((reports, report) => {
    reports[report.role] = report;
    return reports;
  }, {});
}

// ---------------------------------------------------------------------------
// Per-month storage (dashboard_records)
// ---------------------------------------------------------------------------
// One row = one Excel record tagged with its month (period_key). Uploading a
// month upserts only that month (old rows for the period are deleted, new ones
// inserted). Deleting a month removes only that period's rows. This is what
// lets the client "upload just this month" and "delete just one month".

let recordsSchemaPromise: Promise<void> | null = null;
const DASHBOARD_RECORD_INSERT_CHUNK_SIZE = 1000;

function ensureRecordsSchema() {
  recordsSchemaPromise ??= getPostgresPool()
    .query(`
      create table if not exists public.dashboard_records (
        id bigint generated by default as identity primary key,
        role text not null check (role in ('invoice', 'payment')),
        period_key text not null,
        source_filename text not null,
        amount numeric not null,
        customer_name text,
        customer_type text,
        invoice_type text,
        status text,
        document_number text,
        risk_status text,
        uploaded_at timestamptz not null default now()
      );

      create index if not exists dashboard_records_role_period_idx
        on public.dashboard_records (role, period_key);

      create index if not exists dashboard_records_role_uploaded_at_idx
        on public.dashboard_records (role, uploaded_at desc);
    `)
    .then(() => undefined);

  return recordsSchemaPromise;
}

type DashboardRecordRow = {
  role: WorkbookRole;
  period_key: string;
  source_filename: string;
  amount: string;
  customer_name: string | null;
  customer_type: string | null;
  invoice_type: string | null;
  status: string | null;
  document_number: string | null;
  risk_status: string | null;
};

function monthLabelFromPeriodKey(periodKey: string) {
  const [yearStr, monthStr] = periodKey.split("-");
  const year = Number(yearStr);
  const month = Number(monthStr);
  const MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"];

  if (!Number.isFinite(year) || !Number.isFinite(month) || month < 1 || month > 12) {
    return periodKey;
  }

  return `${MONTHS[month]} ${year}`;
}

function recordToDashboardRecord(row: DashboardRecordRow): DashboardRecord {
  const periodKey = row.period_key;
  const periodLabel = monthLabelFromPeriodKey(periodKey);
  const [year, month] = periodKey.split("-").map(Number);
  const periodSort = Number.isFinite(year) && Number.isFinite(month) ? year * 100 + month : null;

  return {
    amount: Number(row.amount),
    customerName: row.customer_name ?? "Unmapped",
    customerType: row.customer_type ?? "Unmapped",
    invoiceType: row.invoice_type ?? "Unmapped",
    status: row.status ?? "Unmapped",
    periodKey,
    periodLabel,
    periodSort,
  };
}

type StoredMonthMeta = {
  period_key: string;
  row_count: number;
  total_amount: string;
  latest_uploaded_at: string;
};

export type StoredMonth = {
  periodKey: string;
  label: string;
  rowCount: number;
  totalAmount: number;
  uploadedAt: string;
};

async function buildSectionForRole(role: WorkbookRole): Promise<DashboardSection | undefined> {
  await ensureRecordsSchema();

  const result = await getPostgresPool().query<DashboardRecordRow>(
    `
      select role, period_key, source_filename, amount::text,
             customer_name, customer_type, invoice_type, status,
             document_number, risk_status
      from public.dashboard_records
      where role = $1
      order by period_key asc;
    `,
    [role],
  );

  if (result.rows.length === 0) {
    return undefined;
  }

  const records = result.rows.map(recordToDashboardRecord);

  return buildSectionFromDbRecords(records, statusOrderByRole(role));
}

export async function listAvailableMonthsForRole(role: WorkbookRole): Promise<StoredMonth[]> {
  await ensureRecordsSchema();

  const result = await getPostgresPool().query<StoredMonthMeta>(
    `
      select period_key, count(*)::int as row_count, sum(amount)::text as total_amount,
             max(uploaded_at)::text as latest_uploaded_at
      from public.dashboard_records
      where role = $1
      group by period_key
      order by period_key desc;
    `,
    [role],
  );

  return result.rows.map((row) => ({
    periodKey: row.period_key,
    label: monthLabelFromPeriodKey(row.period_key),
    rowCount: row.row_count,
    totalAmount: Number(row.total_amount),
    uploadedAt: row.latest_uploaded_at,
  }));
}

// Upsert a single month: delete existing rows for (role, periodKey) then insert
// the new ones inside one transaction.
export async function upsertMonthRecords(
  role: WorkbookRole,
  periodKey: string,
  records: BaseRecord[],
  sourceFilename: string,
): Promise<{ rowCount: number }> {
  await ensureRecordsSchema();

  const pool = getPostgresPool();
  const client = await pool.connect();

  try {
    await client.query("begin");
    await client.query(`delete from public.dashboard_records where role = $1 and period_key = $2;`, [role, periodKey]);

    for (let start = 0; start < records.length; start += DASHBOARD_RECORD_INSERT_CHUNK_SIZE) {
      const chunk = records.slice(start, start + DASHBOARD_RECORD_INSERT_CHUNK_SIZE);

      await client.query(
        `
          insert into public.dashboard_records (
            role, period_key, source_filename, amount,
            customer_name, customer_type, invoice_type, status,
            document_number, risk_status
          )
          select
            $1::text,
            $2::text,
            $3::text,
            record.amount,
            record.customer_name,
            record.customer_type,
            record.invoice_type,
            record.status,
            record.document_number,
            record.risk_status
          from unnest(
            $4::numeric[],
            $5::text[],
            $6::text[],
            $7::text[],
            $8::text[],
            $9::text[],
            $10::text[]
          ) as record(
            amount,
            customer_name,
            customer_type,
            invoice_type,
            status,
            document_number,
            risk_status
          );
        `,
        [
          role,
          periodKey,
          sourceFilename,
          chunk.map((record) => record.amount),
          chunk.map((record) => record.customerName),
          chunk.map((record) => record.customerType),
          chunk.map((record) => record.invoiceType),
          chunk.map((record) => record.status),
          chunk.map((record) => (record as BaseRecord & { documentNumber?: string }).documentNumber ?? null),
          chunk.map((record) => (record as BaseRecord & { riskStatus?: string }).riskStatus ?? null),
        ],
      );
    }

    await client.query("commit");
    return { rowCount: records.length };
  } catch (error) {
    await client.query("rollback");
    throw error;
  } finally {
    client.release();
  }
}

export async function deleteMonthRecords(role: WorkbookRole, periodKey: string): Promise<{ deleted: number }> {
  await ensureRecordsSchema();

  const result = await getPostgresPool().query(
    `delete from public.dashboard_records where role = $1 and period_key = $2;`,
    [role, periodKey],
  );

  return { deleted: result.rowCount ?? 0 };
}

export type AllDashboardReportsResult = {
  reports: PersistedDashboardReports;
  months: Partial<Record<WorkbookRole, StoredMonth[]>>;
};

export async function getAllDashboardReports(role?: WorkbookRole): Promise<AllDashboardReportsResult> {
  const roles: WorkbookRole[] = role ? [role] : ["invoice", "payment"];

  const [reports, months] = await Promise.all([
    Promise.all(
      roles.map(async (currentRole): Promise<[WorkbookRole, PersistedDashboardReport] | null> => {
        const section = await buildSectionForRole(currentRole);
        if (!section) {
          return null;
        }

        const monthsForRole = await listAvailableMonthsForRole(currentRole);
        const latestMonth = monthsForRole[0];

        const report: PersistedDashboardReport = {
          id: 0,
          role: currentRole,
          generatedAt: latestMonth?.uploadedAt ?? new Date().toISOString(),
          file: {
            role: currentRole,
            name: latestMonth ? `Merge ${monthsForRole.length} bulan` : "Dashboard",
            sheetName: currentRole === "invoice" ? "Billing Detail" : "Detail Payment",
            rowCount: section.rowCount,
            totalAmount: section.totalAmount,
          },
          section,
        };

        return [currentRole, report];
      }),
    ),
    Promise.all(
      roles.map(async (currentRole): Promise<[WorkbookRole, StoredMonth[]]> => [
        currentRole,
        await listAvailableMonthsForRole(currentRole),
      ]),
    ),
  ]);

  const reportsMap = reports.reduce<PersistedDashboardReports>((acc, entry) => {
    if (entry) {
      acc[entry[0]] = entry[1];
    }
    return acc;
  }, {});

  const monthsMap = months.reduce<Partial<Record<WorkbookRole, StoredMonth[]>>>((acc, entry) => {
    acc[entry[0]] = entry[1];
    return acc;
  }, {});

  return { reports: reportsMap, months: monthsMap };
}

// Upload handler for the per-month merge model: parse the workbook, group its
// records by period, and upsert each period independently. A workbook with many
// months (initial bulk upload) stores each month separately; a single-month
// workbook only touches that one month.
export async function saveDashboardUploadByMonth(
  role: WorkbookRole,
  file: { name: string; buffer: Buffer },
): Promise<{ upsertedMonths: { periodKey: string; rowCount: number }[] }> {
  const records = parseRecordsFromWorkbook(file, role);

  if (records.length === 0) {
    throw new Error("Tidak ada record valid yang bisa dibaca dari workbook.");
  }

  const byPeriod = groupByPeriod(records);

  if (byPeriod.size === 0) {
    throw new Error("Record di workbook tidak memiliki periode (bulan/tahun) atau tanggal yang bisa dibaca.");
  }

  const upserted: { periodKey: string; rowCount: number }[] = [];

  for (const [periodKey, periodRecords] of byPeriod) {
    const result = await upsertMonthRecords(role, periodKey, periodRecords, file.name);
    upserted.push({ periodKey, rowCount: result.rowCount });
  }

  return { upsertedMonths: upserted };
}

// ---------------------------------------------------------------------------
// Backwards-compat shim: build a MonitoringDashboardData-shaped overview from
// the merged per-month records, used where the upload response still wants to
// echo the parsed section.
// ---------------------------------------------------------------------------
export async function buildOverviewFromStoredRecords(role: WorkbookRole): Promise<DashboardSection | undefined> {
  return buildSectionForRole(role);
}

// Re-exported so the legacy snapshot path keeps compiling if still referenced.
export async function computeFileSha256(buffer: Buffer) {
  return createHash("sha256").update(buffer).digest("hex");
}

// Kept to satisfy the unused buildSection import usage in legacy snapshot path.
export { buildSection };
