import "server-only";

import { createHash } from "node:crypto";

import { buildMonitoringDashboardFromFiles } from "@/lib/monitoring-dashboard";
import { getPostgresPool } from "@/lib/postgres";
import type {
  DashboardSection,
  MonitoringDashboardData,
  PersistedDashboardReport,
  PersistedDashboardReports,
  UploadedWorkbookSummary,
  WorkbookRole,
} from "@/lib/monitoring-dashboard-types";

type SaveDashboardUploadInput = {
  role: WorkbookRole;
  file: {
    name: string;
    type: string;
    size: number;
    buffer: Buffer;
  };
  dashboardData: MonitoringDashboardData;
  fileSummary: UploadedWorkbookSummary;
  section: DashboardSection;
};

type DashboardUploadRow = {
  id: string;
  role: WorkbookRole;
  filename: string;
  sheet_name: string;
  row_count: number;
  total_amount: string;
  section_data: DashboardSection;
  file_data?: Buffer;
  uploaded_at: string;
};

let schemaPromise: Promise<void> | null = null;

function ensureSchema() {
  schemaPromise ??= getPostgresPool()
    .query(`
      create table if not exists public.dashboard_uploads (
        id bigint generated by default as identity primary key,
        role text not null check (role in ('invoice', 'payment')),
        filename text not null,
        sheet_name text not null,
        mime_type text,
        file_size integer not null,
        file_sha256 text not null,
        file_data bytea not null,
        dashboard_data jsonb not null,
        section_data jsonb not null,
        total_amount numeric not null,
        row_count integer not null,
        uploaded_at timestamptz not null default now()
      );

      create index if not exists dashboard_uploads_role_uploaded_at_idx
        on public.dashboard_uploads (role, uploaded_at desc);

      create index if not exists dashboard_uploads_file_sha256_idx
        on public.dashboard_uploads (file_sha256);
    `)
    .then(() => undefined);

  return schemaPromise;
}

function hasFilterRecords(section: DashboardSection) {
  return Array.isArray((section as DashboardSection & { records?: unknown }).records);
}

async function sectionWithFilterRecords(row: DashboardUploadRow) {
  if (hasFilterRecords(row.section_data) || !row.file_data) {
    return row.section_data;
  }

  try {
    const dashboard = buildMonitoringDashboardFromFiles(
      [
        {
          name: row.filename,
          buffer: row.file_data,
        },
      ],
      row.role,
    );

    const section = dashboard[row.role] ?? row.section_data;

    if (hasFilterRecords(section)) {
      await getPostgresPool().query(
        `
          update public.dashboard_uploads
          set section_data = $1::jsonb
          where id = $2;
        `,
        [JSON.stringify(section), row.id],
      );
    }

    return section;
  } catch {
    return row.section_data;
  }
}

async function toPersistedReport(row: DashboardUploadRow): Promise<PersistedDashboardReport> {
  const role = row.role;
  const section = await sectionWithFilterRecords(row);

  return {
    id: Number(row.id),
    role,
    generatedAt: row.uploaded_at,
    file: {
      role,
      name: row.filename,
      sheetName: row.sheet_name,
      rowCount: row.row_count,
      totalAmount: Number(row.total_amount),
    },
    section,
  };
}

export async function saveDashboardUpload(input: SaveDashboardUploadInput): Promise<PersistedDashboardReport> {
  await ensureSchema();

  const fileHash = createHash("sha256").update(input.file.buffer).digest("hex");
  const result = await getPostgresPool().query<DashboardUploadRow>(
    `
      insert into public.dashboard_uploads (
        role,
        filename,
        sheet_name,
        mime_type,
        file_size,
        file_sha256,
        file_data,
        dashboard_data,
        section_data,
        total_amount,
        row_count
      )
      values ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9::jsonb, $10, $11)
      returning id, role, filename, sheet_name, row_count, total_amount::text, section_data, uploaded_at::text;
    `,
    [
      input.role,
      input.file.name,
      input.fileSummary.sheetName,
      input.file.type || "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      input.file.size,
      fileHash,
      input.file.buffer,
      JSON.stringify(input.dashboardData),
      JSON.stringify(input.section),
      input.fileSummary.totalAmount,
      input.fileSummary.rowCount,
    ],
  );

  return toPersistedReport(result.rows[0]);
}

export async function getLatestDashboardReports(role?: WorkbookRole): Promise<PersistedDashboardReports> {
  await ensureSchema();

  const result = await getPostgresPool().query<DashboardUploadRow>(
    role
      ? `
        select distinct on (role)
          id, role, filename, sheet_name, row_count, total_amount::text, section_data,
          case when section_data ? 'records' then null else file_data end as file_data,
          uploaded_at::text
        from public.dashboard_uploads
        where role = $1
        order by role, uploaded_at desc;
      `
      : `
        select distinct on (role)
          id, role, filename, sheet_name, row_count, total_amount::text, section_data,
          case when section_data ? 'records' then null else file_data end as file_data,
          uploaded_at::text
        from public.dashboard_uploads
        order by role, uploaded_at desc;
      `,
    role ? [role] : [],
  );

  const persistedReports = await Promise.all(result.rows.map((row) => toPersistedReport(row)));

  return persistedReports.reduce<PersistedDashboardReports>((reports, report) => {
    reports[report.role] = report;
    return reports;
  }, {});
}
