import "server-only";

import { getPostgresPool } from "@/lib/postgres";
import { parseExportRecordsFromWorkbook } from "@/lib/monitoring-dashboard";
import type {
  ExportDashboardPayload,
  ExportRecord,
  ExportStoredMonth,
} from "@/lib/export-dashboard-types";

const INSERT_CHUNK_SIZE = 500;
let exportSchemaPromise: Promise<void> | null = null;

function ensureExportSchema() {
  exportSchemaPromise ??= getPostgresPool()
    .query(`
      create table if not exists public.export_records (
        id bigint generated by default as identity primary key,
        period_key text not null,
        source_filename text not null,
        record_data jsonb not null,
        uploaded_at timestamptz not null default now()
      );

      create index if not exists export_records_period_idx
        on public.export_records (period_key);

      create index if not exists export_records_uploaded_at_idx
        on public.export_records (uploaded_at desc);
    `)
    .then(() => undefined);

  return exportSchemaPromise;
}

function monthLabelFromPeriodKey(periodKey: string) {
  const monthNames = ["", "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"];
  const [yearText, monthText] = periodKey.split("-");
  const year = Number(yearText);
  const month = Number(monthText);

  return Number.isFinite(year) && month >= 1 && month <= 12
    ? `${monthNames[month]} ${year}`
    : periodKey;
}

async function replaceExportMonth(periodKey: string, records: ExportRecord[], filename: string) {
  const client = await getPostgresPool().connect();

  try {
    await client.query("begin");
    await client.query(`delete from public.export_records where period_key = $1;`, [periodKey]);

    for (let start = 0; start < records.length; start += INSERT_CHUNK_SIZE) {
      const chunk = records.slice(start, start + INSERT_CHUNK_SIZE);

      await client.query(
        `
          insert into public.export_records (period_key, source_filename, record_data)
          select $1::text, $2::text, value
          from unnest($3::jsonb[]) as value;
        `,
        [periodKey, filename, chunk.map((record) => JSON.stringify(record))],
      );
    }

    await client.query("commit");
  } catch (error) {
    await client.query("rollback");
    throw error;
  } finally {
    client.release();
  }
}

export async function saveExportUploadByMonth(file: { name: string; buffer: Buffer }) {
  await ensureExportSchema();
  const records = parseExportRecordsFromWorkbook(file);
  const grouped = new Map<string, ExportRecord[]>();

  for (const record of records) {
    const monthRecords = grouped.get(record.periodKey) ?? [];
    monthRecords.push(record);
    grouped.set(record.periodKey, monthRecords);
  }

  for (const [periodKey, monthRecords] of grouped) {
    await replaceExportMonth(periodKey, monthRecords, file.name);
  }

  return {
    upsertedMonths: [...grouped.entries()].map(([periodKey, monthRecords]) => ({
      periodKey,
      rowCount: monthRecords.length,
    })),
  };
}

type ExportRecordRow = {
  source_filename: string;
  record_data: ExportRecord;
  uploaded_at: string;
};

type ExportMonthRow = {
  period_key: string;
  row_count: number;
  total_usd: string;
  total_tonnage: string;
  latest_uploaded_at: string;
};

export async function getExportDashboard(): Promise<ExportDashboardPayload> {
  await ensureExportSchema();

  const [recordsResult, monthsResult] = await Promise.all([
    getPostgresPool().query<ExportRecordRow>(
      `
        select source_filename, record_data, uploaded_at::text
        from public.export_records
        order by period_key asc, id asc;
      `,
    ),
    getPostgresPool().query<ExportMonthRow>(
      `
        select
          period_key,
          count(*)::int as row_count,
          coalesce(sum((record_data->>'usdValue')::numeric), 0)::text as total_usd,
          coalesce(sum((record_data->>'tonnage')::numeric), 0)::text as total_tonnage,
          max(uploaded_at)::text as latest_uploaded_at
        from public.export_records
        group by period_key
        order by period_key desc;
      `,
    ),
  ]);

  const latestRow = [...recordsResult.rows].sort(
    (left, right) => new Date(right.uploaded_at).getTime() - new Date(left.uploaded_at).getTime(),
  )[0];
  const months: ExportStoredMonth[] = monthsResult.rows.map((row) => ({
    periodKey: row.period_key,
    label: monthLabelFromPeriodKey(row.period_key),
    rowCount: row.row_count,
    totalUsd: Number(row.total_usd),
    totalTonnage: Number(row.total_tonnage),
    uploadedAt: row.latest_uploaded_at,
  }));

  return {
    generatedAt: latestRow?.uploaded_at ?? null,
    filename: latestRow?.source_filename ?? null,
    sheetName: "Data Ekspor",
    records: recordsResult.rows.map((row) => row.record_data),
    months,
  };
}

export async function deleteExportMonth(periodKey: string) {
  await ensureExportSchema();
  const result = await getPostgresPool().query(
    `delete from public.export_records where period_key = $1;`,
    [periodKey],
  );

  return { deleted: result.rowCount ?? 0 };
}
